name: docker-compose-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ubuntu checksec
        run: docker-compose run checksec-ubuntu
      - name: arch checksec
        run: docker-compose run checksec-arch